version: "3"
services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile

    ports:
      - 80:80

    volumes:
      - ./public:/app

    depends_on:
      - db
    links:
      - db

  db:
    image: mysql
    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strategie_test
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
